### PR TITLE
Elevation lookup

### PR DESCRIPTION
**Pull request by dspreitz**
Please review, this code proposal.

### CODE REVIEW

**Comment by tobiz** [comment]
Dominic,

Have had a quick look through these and they look ok.  I've not merged 
them yet but will do so.

Peter

**Comment by tobiz** [comment]
Dominic,

I'm holding off merging your proposal as I'm having a problem with an 
enhancement I've coded in process_log.py.

The enhancement is to include 'short' flights eg simulate cable breaks 
etc.  The idea being that it also tests that a minimum altitude has been 
attained to count it as a flight.  When I've resolved the problem I'm 
having with this I'll merge your code. Note the merge might not happen 
now till later this month.

Rgds

Peter
_Skype:_ tobizskype

**Comment by dspreitz** [comment]
Peter,

thanks for the info. Why are you not coding your 
short-flight-improvement in a dedicated git branch in your local git?

https://www.atlassian.com/git/tutorials/using-branches/git-merge

I am quite busy at work atm. I'll try to get back to finishing the 
OGN_db code over the weekend.

Dominic

Am 09.06.15 um 23:38 schrieb tobiz:

> Dominic,
> 
> I'm holding off merging your proposal as I'm having a problem with an
> enhancement I've coded in process_log.py.
> 
> The enhancement is to include 'short' flights eg simulate cable breaks
> etc. The idea being that it also tests that a minimum altitude has been
> attained to count it as a flight. When I've resolved the problem I'm
> having with this I'll merge your code. Note the merge might not happen
> now till later this month.
> 
> Rgds
> 
> Peter
> _Skype:_ tobizskype
> On 07/06/15 15:04, Dominic Spreitz wrote:
> 
> > Please review, this code proposal.
> > 
> > ---
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/tobiz/OGN-Flight-Logger/pull/16
> > 
> > Commit Summary
> > - Changed elevation lookup to use lat/lon
> > - Added elevation lookup based on lat/lon
> > - Deleted OGN_db.py. Has nothing to do with this branch
> > - Updated .gitignore
> > 
> > File Changes
> > - _M_ .gitignore
> >   https://github.com/tobiz/OGN-Flight-Logger/pull/16/files#diff-0
> >   (19)
> > - _M_ flogger.py
> >   https://github.com/tobiz/OGN-Flight-Logger/pull/16/files#diff-1 (7)
> > - _M_ flogger.sql3
> >   https://github.com/tobiz/OGN-Flight-Logger/pull/16/files#diff-2 (0)
> > - _M_ settings.py
> >   https://github.com/tobiz/OGN-Flight-Logger/pull/16/files#diff-3 (8)
> > 
> > Patch Links:
> > - https://github.com/tobiz/OGN-Flight-Logger/pull/16.patch
> > - https://github.com/tobiz/OGN-Flight-Logger/pull/16.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/tobiz/OGN-Flight-Logger/pull/16.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/tobiz/OGN-Flight-Logger/pull/16#issuecomment-110511486.

## 

Dominic Spreitz
Kothauer Str. 123a
85053 Ingolstadt
Germany

Mobil: +49.179.9016643

**Comment by tobiz** [comment]
Dominic,

Re use of a dedicated local git branch: yes I should be and will do so 
for all future work (I just didn't set it up like that at the start).

However, I too am busy for the next two weeks and making significant 
changes to ways of working at this time is not advisable.

I hope to get your merge incorporated before the weekend; I'll let you know.

Peter

**Comment by tobiz** [comment]
Dominic
I've add you as a collaborator as I won't be doing anything for the next 2 weeks

Peter

**Pull request merged**
